//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallet.Services.Telegram.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TelegramBot
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelegramBot()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wallet.Services.Telegram.Resources.TelegramBot", typeof(TelegramBot).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share Location.
        /// </summary>
        internal static string AmountEnteredStateDefinitionBase_CreateReplyKeyboardMarkup_Share_Location
        {
            get
            {
                return ResourceManager.GetString("AmountEnteredStateDefinitionBase_CreateReplyKeyboardMarkup_Share_Location", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter the amount for category {0}!.
        /// </summary>
        internal static string ExpenseAmountEnteredStateDefinition_ConfigureState_Please_enter_the_amount_for_category__0__
        {
            get
            {
                return ResourceManager.GetString("ExpenseAmountEnteredStateDefinition_ConfigureState_Please_enter_the_amount_for_ca" +
                        "tegory__0__", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You entered amount {0} for category {1}.
        /// </summary>
        internal static string ExpenseAmountEnteredStateDefinition_ConfigureState_You_entered_amount__0__for_category__1_
        {
            get
            {
                return ResourceManager.GetString("ExpenseAmountEnteredStateDefinition_ConfigureState_You_entered_amount__0__for_cat" +
                        "egory__1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You selected category {0}!.
        /// </summary>
        internal static string ExpenseCategorySelectedStateDefinition_ConfigureState_You_selected_category__0__
        {
            get
            {
                return ResourceManager.GetString("ExpenseCategorySelectedStateDefinition_ConfigureState_You_selected_category__0__", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string ExpensesStateDefinition_ConfigureState_CategorySelected
        {
            get
            {
                return ResourceManager.GetString("ExpensesStateDefinition_ConfigureState_CategorySelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please try again.
        /// </summary>
        internal static string IdleStateDefinition_ConfigureState_Invalid_input__Please_try_again
        {
            get
            {
                return ResourceManager.GetString("IdleStateDefinition_ConfigureState_Invalid_input__Please_try_again", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please choose {0} or {1} transaction.
        /// </summary>
        internal static string IdleStateDefinition_ConfigureState_Please_choose__0__or__1__transaction
        {
            get
            {
                return ResourceManager.GetString("IdleStateDefinition_ConfigureState_Please_choose__0__or__1__transaction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string IdleStateDefinition_CreateReplyKeyboardMarkup_Expenses
        {
            get
            {
                return ResourceManager.GetString("IdleStateDefinition_CreateReplyKeyboardMarkup_Expenses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string IdleStateDefinition_CreateReplyKeyboardMarkup_Income
        {
            get
            {
                return ResourceManager.GetString("IdleStateDefinition_CreateReplyKeyboardMarkup_Income", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amount {0} is not valid. Please enter a valid amount..
        /// </summary>
        internal static string IncomeAmountEnteredStateDefinition_ConfigureState_Amount__0__is_not_valid__Please_enter_a_valid_amount_
        {
            get
            {
                return ResourceManager.GetString("IncomeAmountEnteredStateDefinition_ConfigureState_Amount__0__is_not_valid__Please" +
                        "_enter_a_valid_amount_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transaction  {0} has been saved..
        /// </summary>
        internal static string IncomeAmountEnteredStateDefinition_ConfigureState_Transaction___0__has_been_saved_
        {
            get
            {
                return ResourceManager.GetString("IncomeAmountEnteredStateDefinition_ConfigureState_Transaction___0__has_been_saved" +
                        "_", resourceCulture);
            }
        }
    }
}
