services:
  database:
    container_name: "postgres"
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - network

  rabbitmq:
    container_name: "rabbitmq"
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - network

  api-identity:
    container_name: "api-identity"
    build:
      context: .
      dockerfile: src/API.Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SECRET=${SECRET}
    ports:
      - "5000:8080"
    depends_on:
      - database
      - rabbitmq
    volumes:
      - data_protection_keys:/app/keys
    networks:
      - network

  api-finance:
    container_name: "api-finance"
    build:
      context: .
      dockerfile: src/API.Finance/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SECRET=${SECRET}
    ports:
      - "5001:8080"
    depends_on:
      - database
      - rabbitmq
    volumes:
      - data_protection_keys:/app/keys
    networks:
      - network

  api-telegram:
    container_name: "api-telegram"
    build:
      context: .
      dockerfile: src/API.Telegram/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SECRET=${SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WALLET_API_TOKEN=${WALLET_API_TOKEN}
    depends_on:
      - database
      - rabbitmq
    volumes:
      - data_protection_keys:/app/keys
    networks:
      - network
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data:
  rabbitmq_data:
  data_protection_keys:

networks:
  network:
    driver: bridge

