<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
		<PackageReference Include="RabbitMQ.Client" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Microsoft.Extensions.Hosting.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Wallet.Application.Finance\Wallet.Application.Finance.csproj" />
		<ProjectReference Include="..\Wallet.Domain.Contracts\Wallet.Domain.Contracts.csproj" />
		<ProjectReference Include="..\Wallet.Shared\Wallet.Shared.csproj" />
	</ItemGroup>
</Project>
