<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<InvariantGlobalization>false</InvariantGlobalization>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
		<DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Flurl.Http" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="RabbitMQ.Client" />
		<PackageReference Include="Stateless" />
		<PackageReference Include="Telegram.Bot" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<Reference Include="Microsoft.Extensions.Hosting.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\..\.dockerignore">
			<Link>.dockerignore</Link>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Wallet.Domain.Contracts\Wallet.Domain.Contracts.csproj" />
		<ProjectReference Include="..\Wallet.Domain.Entities\Wallet.Domain.Entities.csproj" />
		<ProjectReference Include="..\Wallet.Infrastructure.LoggerService\Wallet.Infrastructure.LoggerService.csproj" />
		<ProjectReference Include="..\Wallet.Shared\Wallet.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\TelegramBot.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>TelegramBot.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\TelegramBot.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>TelegramBot.resx</DependentUpon>
		</Compile>
	</ItemGroup>
</Project>
