apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegramservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegramservice
  template:
    metadata:
      labels:
        app: telegramservice
    spec:
      containers:
        - name: telegramservice
          image: vzabila/telegramservice:latest
          env:
            - name: TelegramBotToken
              valueFrom:
                secretKeyRef:
                  name: telegramservice-secret
                  key: TelegramBotToken
---
apiVersion: v1
kind: Service
metadata:
  name: telegramservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: telegramservice
  ports:
    - name: telegramservice
      protocol: TCP
      port: 80
      targetPort: 80
