<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Wallet.Domain.Contracts\Wallet.Domain.Contracts.csproj" />
		<ProjectReference Include="..\Wallet.Domain.Entities\Wallet.Domain.Entities.csproj" />
	</ItemGroup>

</Project>
