<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.AspNetCore.Identity" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Wallet.Domain.Contracts\Wallet.Domain.Contracts.csproj" />
		<ProjectReference Include="..\Wallet.Shared\Wallet.Shared.csproj" />
	</ItemGroup>

</Project>
