using AutoFixture;
using FluentAssertions;
using TestUtilities.Fixtures;
using Xunit;

namespace TestUtilities.UnitTests.Fixtures;

public class TestFixtureTests
{
    private sealed class TestableTestFixture : TestFixture
    {
        public IFixture GetFixture() => Fixture;

        public new T Create<T>() => base.Create<T>();
        public new T[] CreateMany<T>(int count = 3) => base.CreateMany<T>(count);
        public new T Build<T>(Action<T> configure) where T : class => base.Build<T>(configure);
    }

    private sealed class TestClass
    {
        public string Name { get; set; } = string.Empty;
        public int Age { get; set; }
        public DateTime CreatedAt { get; set; }
    }

    [Fact]
    public void Constructor_ShouldInitializeFixture()
    {
        // Act
        var testFixture = new TestableTestFixture();

        // Assert
        testFixture.GetFixture().Should().NotBeNull();
    }

    [Fact]
    public void Constructor_ShouldConfigureFixtureWithOmitOnRecursionBehavior()
    {
        // Act
        var testFixture = new TestableTestFixture();
        var fixture = testFixture.GetFixture();

        // Assert
        fixture.Behaviors.Should().ContainSingle(b => b is OmitOnRecursionBehavior);
        fixture.Behaviors.Should().NotContain(b => b is ThrowingRecursionBehavior);
    }

    [Fact]
    public void Create_ShouldReturnInstanceOfSpecifiedType()
    {
        // Arrange
        var testFixture = new TestableTestFixture();

        // Act
        var result = testFixture.Create<TestClass>();

        // Assert
        result.Should().NotBeNull();
        result.Should().BeOfType<TestClass>();
    }

    [Fact]
    public void Create_ShouldReturnDifferentInstances_OnMultipleCalls()
    {
        // Arrange
        var testFixture = new TestableTestFixture();

        // Act
        var result1 = testFixture.Create<TestClass>();
        var result2 = testFixture.Create<TestClass>();

        // Assert
        result1.Should().NotBeSameAs(result2);
    }

    [Fact]
    public void Create_ShouldPopulatePropertiesWithRandomValues()
    {
        // Arrange
        var testFixture = new TestableTestFixture();

        // Act
        var result = testFixture.Create<TestClass>();

        // Assert
        result.Name.Should().NotBeNullOrEmpty();
        result.Age.Should().NotBe(0);
        result.CreatedAt.Should().NotBe(default);
    }

    [Fact]
    public void CreateMany_ShouldReturnDefaultNumberOfInstances()
    {
        // Arrange
        var testFixture = new TestableTestFixture();

        // Act
        var results = testFixture.CreateMany<TestClass>();

        // Assert
        results.Should().HaveCount(3); // Default count
        results.Should().AllBeOfType<TestClass>();
    }

    [Theory]
    [InlineData(1)]
    [InlineData(5)]
    [InlineData(10)]
    public void CreateMany_ShouldReturnSpecifiedNumberOfInstances(int count)
    {
        // Arrange
        var testFixture = new TestableTestFixture();

        // Act
        var results = testFixture.CreateMany<TestClass>(count);

        // Assert
        results.Should().HaveCount(count);
        results.Should().AllBeOfType<TestClass>();
    }

    [Fact]
    public void CreateMany_ShouldReturnUniqueInstances()
    {
        // Arrange
        var testFixture = new TestableTestFixture();

        // Act
        var results = testFixture.CreateMany<TestClass>(5);

        // Assert
        results.Should().OnlyHaveUniqueItems();
    }

    [Fact]
    public void Build_ShouldReturnInstanceWithCustomConfiguration()
    {
        // Arrange
        var testFixture = new TestableTestFixture();
        const string customName = "Custom Name";
        const int customAge = 25;

        // Act
        var result = testFixture.Build<TestClass>(instance =>
        {
            instance.Name = customName;
            instance.Age = customAge;
        });

        // Assert
        result.Should().NotBeNull();
        result.Name.Should().Be(customName);
        result.Age.Should().Be(customAge);
    }

    [Fact]
    public void Build_ShouldKeepAutoGeneratedValues_WhenNotExplicitlySet()
    {
        // Arrange
        var testFixture = new TestableTestFixture();
        const string customName = "Custom Name";

        // Act
        var result = testFixture.Build<TestClass>(instance =>
        {
            instance.Name = customName;
        });

        // Assert
        result.Name.Should().Be(customName);
        result.Age.Should().NotBe(0); // Should have auto-generated value
        result.CreatedAt.Should().NotBe(default); // Should have auto-generated value
    }

    [Fact]
    public void Build_ShouldAllowMultipleConfigurations()
    {
        // Arrange
        var testFixture = new TestableTestFixture();
        const string customName = "Custom Name";
        const int customAge = 30;
        var customCreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        // Act
        var result = testFixture.Build<TestClass>(instance =>
        {
            instance.Name = customName;
            instance.Age = customAge;
            instance.CreatedAt = customCreatedAt;
        });

        // Assert
        result.Name.Should().Be(customName);
        result.Age.Should().Be(customAge);
        result.CreatedAt.Should().Be(customCreatedAt);
    }

    [Fact]
    public void Create_ShouldWorkWithValueTypes()
    {
        // Arrange
        var testFixture = new TestableTestFixture();

        // Act
        var intResult = testFixture.Create<int>();
        var decimalResult = testFixture.Create<decimal>();
        var guidResult = testFixture.Create<Guid>();

        // Assert
        intResult.Should().NotBe(0);
        decimalResult.Should().NotBe(0);
        guidResult.Should().NotBe(Guid.Empty);
    }

    [Fact]
    public void Create_ShouldWorkWithString()
    {
        // Arrange
        var testFixture = new TestableTestFixture();

        // Act
        var result = testFixture.Create<string>();

        // Assert
        result.Should().NotBeNullOrEmpty();
    }

    [Fact]
    public void Create_ShouldWorkWithDateTime()
    {
        // Arrange
        var testFixture = new TestableTestFixture();

        // Act
        var result = testFixture.Create<DateTime>();

        // Assert
        result.Should().NotBe(default);
    }

    [Fact]
    public void CreateMany_ShouldWorkWithValueTypes()
    {
        // Arrange
        var testFixture = new TestableTestFixture();

        // Act
        var results = testFixture.CreateMany<int>(5);

        // Assert
        results.Should().HaveCount(5);
        results.Should().OnlyHaveUniqueItems();
        results.Should().NotContain(0);
    }

    [Fact]
    public void CustomAutoDataAttribute_ShouldCreateInstance()
    {
        // Act
        var attribute = new CustomAutoDataAttribute();

        // Assert
        attribute.Should().NotBeNull();
        attribute.Should().BeAssignableTo<AutoFixture.Xunit2.AutoDataAttribute>();
    }

    private sealed class CustomTestFixture : TestFixture
    {
        public bool ConfigureCalled { get; private set; }

        protected override void ConfigureFixture()
        {
            base.ConfigureFixture();
            ConfigureCalled = true;

            // Example custom configuration
            Fixture.Customize<TestClass>(composer =>
                composer.With(x => x.Name, "CustomName"));
        }

        // Expose protected methods for testing
        public new T Create<T>() => base.Create<T>();
    }

    [Fact]
    public void ConfigureFixture_ShouldBeCalledInConstructor()
    {
        // Act
        var testFixture = new CustomTestFixture();

        // Assert
        testFixture.ConfigureCalled.Should().BeTrue();
    }

    [Fact]
    public void ConfigureFixture_ShouldAllowCustomization()
    {
        // Arrange
        var testFixture = new CustomTestFixture();

        // Act
        var result = testFixture.Create<TestClass>();

        // Assert
        result.Name.Should().Be("CustomName");
    }
}
