services:
  database:
    container_name: "wallet-postgres"
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  rabbitmq:
    container_name: "wallet-rabbitmq"
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  
  wallet-api-identity:
    container_name: "wallet-api-identity"
    image: vzabila/wallet-api-identity
    build: 
      context: .
      dockerfile: ./src/Wallet.Api.Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
    depends_on:
      - database
      - rabbitmq  
  wallet-api-finance:
    container_name: "wallet-api-finance"
    image: vzabila/wallet-api-finance
    build: 
      context: .
      dockerfile: ./src/Wallet.Api.Finance/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
    depends_on:
      - database
      - rabbitmq
  wallet-api-telegram:
    container_name: "wallet-api-telegram"
    image: vzabila/wallet-api-telegram
    build: 
      context: .
      dockerfile: ./src/Wallet.Api.Telegram/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"
    depends_on:
      - database
      - rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: